site_name: ZZPO Project documentation
copyright: ZZPO Team

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - Dokumentacja kodu: 'docs.md'
  - API Reference:
    - Player: 'api_reference/player_reference.md'
    - Virus: 'api_reference/virus_reference.md'
    - Cell: 'api_reference/cell_reference.md'
    - Enemy: 'api_reference/enemy_reference.md'
    - Enemy Bullet: 'api_reference/enemy_bullet_reference.md'
    - Bullet: 'api_reference/bullet_reference.md'

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

